# Generated by Django 4.0.4 on 2022-05-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=35, null=True)),
                ('descripction', models.CharField(blank=True, max_length=35, null=True)),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
