# Generated by Django 4.0.4 on 2022-05-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='descripction',
            field=models.CharField(default=3, max_length=35),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(default=4, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default=23, max_length=35),
            preserve_default=False,
        ),
    ]
